# Generated by Django 3.1.7 on 2021-03-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShopTask', '0002_auto_20210308_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customization_option',
        ),
        migrations.AddField(
            model_name='customization',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customizations', related_query_name='customization', to='CoffeeShopTask.product'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.CreateModel(
            name='CustomerOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoffeeShopTask.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoffeeShopTask.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='orders', through='CoffeeShopTask.CustomerOrders', to='CoffeeShopTask.Product'),
        ),
    ]
