# Generated by Django 3.1.7 on 2021-03-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShopTask', '0003_auto_20210309_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customization_option',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customization',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customizations', related_query_name='customizations', to='CoffeeShopTask.product'),
        ),
    ]
