# Generated by Django 3.1.7 on 2021-03-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShopTask', '0004_auto_20210309_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customization_option',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='CoffeeShopTask.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='customization_option',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
