# Generated by Django 3.1.7 on 2021-03-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShopTask', '0005_auto_20210309_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customization_option',
        ),
        migrations.AddField(
            model_name='order',
            name='customization_options',
            field=models.ManyToManyField(related_name='orders', to='CoffeeShopTask.Customization'),
        ),
        migrations.DeleteModel(
            name='CustomerOrders',
        ),
    ]
